# This workflow will publish npm package on release
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: "@devdanim"
      - run: mkdir /tmp/framefusion
      - run: cp -r . /tmp/framefusion
        working-directory: /tmp/framefusion
      - run: yarn install --frozen-lockfile
        working-directory: /tmp/framefusion
      - run: yarn build
        working-directory: /tmp/framefusion
      - run: yarn publish
        working-directory: /tmp/framefusion
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
